//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChairTicket
    {
        public int ID { get; set; }
        public int ID_Chair { get; set; }
        public int ID_Ticket { get; set; }
    
        public virtual Chair Chair { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
