//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.MovieSchedules = new HashSet<MovieSchedule>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Directors { get; set; }
        public string Cast { get; set; }
        public int Timer { get; set; }
        public int Age { get; set; }
        public string Image { get; set; }
        public int ID_MovieGenre { get; set; }
        public int ID_FilmStudio { get; set; }
    
        public virtual FilmStudio FilmStudio { get; set; }
        public virtual MovieGenre MovieGenre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieSchedule> MovieSchedules { get; set; }
    }
}
