//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovieSchedule()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int ID { get; set; }
        public System.TimeSpan TimeStart { get; set; }
        public int ID_Film { get; set; }
        public int ID_Room { get; set; }
        public int PriceFilm { get; set; }
        public bool Status { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
